name:                ibew
version:             0.1.0.0
github:              "idgd/ibew"
license:             AGPL-3.0-or-later
author:              "blank"
maintainer:          "blankneue@proton.me"
copyright:           "blank"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Plural-first instant messaging.

language: GHC2021

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- crypton
- dhall
- monad-logger
- mtl
- persistent
- persistent-sqlite
- random
- servant-client
- servant-multipart
- servant-server
- servant-websockets
- text
- time
- transformers
- wai
- warp
- warp-tls
- websockets

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ibew-exe:
    main:                Main.lhs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ibew

tests:
  ibew-test:
    main:                Spec.lhs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ibew
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
